language: python
# command to install dependencies
before_install:
  - sudo apt-get update
  - sudo apt-get install -y p7zip-full
install:
  - pip install coursera-dl edx-dl


before_script:
  - mkdir project
  - cd project

# command to run tests
script:
  - edx-dl -u $NAME -p $PASS https://courses.edx.org/courses/DavidsonX/D003x.2/2T2015/course/
  - 7za a -tzip myapp.zip -r Downloaded/
  #- rm -rf Downloaded/
  

    
deploy:
  provider: bintray
  file: file1.json
  skip_cleanup: true
  user: sumankhanal
  key: $BTRAY
  on:
    tags: true



# deploy:
#   provider: releases
#   api_key: $GITHUB_TOKEN
#   file: myapp.zip
#   draft: true
#   skip_cleanup: true
#   on:
#     tags: false
  

