language: python
# command to install dependencies
before_install:
  - sudo apt-get update
  - sudo apt-get install -y p7zip-full
install:
  - pip install coursera-dl edx-dl



# command to run tests
script:
  #- curl -fL https://getcli.jfrog.io | sh
  - edx-dl -u $NAME -p $PASS https://courses.edx.org/courses/course-v1:MDAndersonX+CERTaIN.1x+3T2018/course/
  - 7za a -tzip myapp.zip -r Downloaded/
  - rm -rf Downloaded/
  - export JFROG_CLI_HOME_DIR=~/.jfrog
  - jfrog bt --user=sumankhanal --key=$BTRAY --publish=true --override=true u myapp.zip sumankhanal/edx/video
  


# deploy:
#   provider: releases
#   api_key: $GITHUB_TOKEN
#   file: myapp.zip
#   draft: true
#   skip_cleanup: true
#   on:
#     tags: false
  

