language: python
python:
  - 3.6 
# command to install dependencies
before_install:
  - sudo apt-get update
  - sudo apt-get install -y p7zip-full
install:
  - pip install coursera-dl edx-dl


# command to run tests
script:
  - edx-dl -u suman12029@yahoo.co.uk -p Kathmandu123 https://courses.edx.org/courses/HarvardX/HSPH-HMS214x/2013_SOND/course/
  - 7za a -tzip myapp.zip -r Downloaded\*.mp4
  
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: directory/**/*.mp4
  skip_cleanup: true
  on:
    tags: false
