language: python
# command to install dependencies
before_install:
  - sudo apt-get update
  - sudo apt-get install -y p7zip-full
install:
  - pip install coursera-dl edx-dl




# command to run tests
script:
  - edx-dl -u $NAME -p $PASS https://courses.edx.org/courses/HarvardX/HSPH-HMS214x/2013_SOND/course/
  
cache:
   directories:
    - Downloaded/
  
deploy:
  provider: bintray
  file: file1.json
  user: sumankhanal
  key: $BTRAY
  skip_cleanup: true 
  on:
    all_branches: true
    tags: false
