language: python
services:
  - docker

before_install:
  - docker build -t sumankhanal/pichu .
  
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sumankhanal/pichu
