language: bash

services:
  - docker

before_install:
- docker build -t sumankhanal/texive-2017 .

script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
- docker push sumankhanal/texlive-2017
