language: python
services:
  - docker

before_install:
  - docker run -it -v $pwd:/home -w /home sumankhanal/texlive-2018 bin/bash
  
script:
  - pdflatex -shell-escape -synctex=1 -interaction=nonstopmode Beautiful_template.tex
